version: '3.8'

services:
  postgres:
    build: .
    container_name: container_postgres
    environment:
      POSTGRES_DB: webshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

