name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (change if using a different branch)

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Specify Node.js version compatible with your Angular project

    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build Angular project
      run: npm run build -- --output-path=dist --base-href /  # Ensure output is in 'dist' folder
      working-directory: ./frontend

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist
